jwt:
  secret: sc4r4n0D3v
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: root
    database: auth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082